services:
  - type: web
    name: client-management-app
    env: node
    buildCommand: npm ci && npx vite build && mkdir -p dist/server && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist/server
    startCommand: NODE_ENV=production node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false